name: login_with_flutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_facebook_login: ^3.0.0
  country_pickers: ^1.1.0
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  google_sign_in: ^4.0.7
  progress_dialog: ^1.2.0
  flutter_launcher_icons: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "images/launcher/ic_launcher.png"
  image_path_android: "images/launcher/ic_launcher.png"

flutter:

  uses-material-design: true

  assets:
    - images/
  #  - images/a_dot_ham.jpeg